### PR TITLE
change how elevation is set

### PR DESCRIPTION
**Pull request by rahulkgupta**
elevation isnt an input in the geomodal. On save, the elevation is fetched from the cloud function and set

### CODE REVIEW

**Review by vincentfretin — COMMENTED** [review]
I didn't test, but the changes seems okay to me.

**Comment by vincentfretin** [comment]
You can address my comment https://github.com/3DStreet/3dstreet/issues/770#issuecomment-2311979099 in this PR if you want, or we can do the change after the merge.

**Comment by kfarr** [comment]
this is a good step forward:
- it was unclear after clicking update why the modal wasn't closing. obviously the answer is waiting for remote server. i wonder if there's a way to copy the save indicator

**Review by kfarr — APPROVED** [review]

**Review by rahulkgupta — COMMENTED** [review]
nice!

**Pull request merged**
