### PR TITLE
update aframe-loader-3dtiles-component: fix load errors

### PR DESCRIPTION
**Pull request by Algorush**
Added check for `this.viewportSize` to the `Tick` function in `aframe-loader-3dtiles-component.js` to prevent error with undefined value described in this issue: https://github.com/3DStreet/3dstreet/issues/633
Also same issue: https://github.com/3DStreet/3dstreet/issues/661

### CODE REVIEW

**Comment by vincentfretin** [comment]
Is this https://github.com/3DStreet/aframe-loader-3dtiles-component/pull/9 ? This PR should really be on the board in the review column.
Does the other PRs in https://github.com/3DStreet/aframe-loader-3dtiles-component/pulls also in the build? If yes those should be merged there.

**Comment by Algorush** [comment]
> This PR should really be on the board in the review column.

yes, you right. Otherwise it gets confusing. I will remove PRs in 3DStreet

**Comment by Algorush** [comment]
Closed, because already have this PR: https://github.com/3DStreet/aframe-loader-3dtiles-component/pull/9

**Comment by vincentfretin** [comment]
Yeah but you need to copy the file in 3dstreet repository, so you still need this PR.

**Comment by kfarr** [comment]
Do we need both the minified and unminified versions here? @Algorush

**Comment by kfarr** [comment]
@Algorush I will wait to merge this until you can confirm that the https://github.com/3DStreet/aframe-loader-3dtiles-component/ repo is actually up-to-date with what is intended to be in the 3dstreet repo

**Comment by Algorush** [comment]
Updated lib to the last version in last commit

**Pull request merged**
