### PR TITLE
Undo create/remove entity, add/remove component

### LINKED ISSUE #704: additional undo commands to support autosave
list of things? (in another issue)

- entity create / remove
- component add / component remove

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #704

Lots of refactoring here.
Although I manually tested all that, please do some tests on your own to be sure I didn't break anything and all is working correctly.

### CODE REVIEW

**Comment by vincentfretin** [comment]
I asked Claude Sonnet 3.5 on the code base via Cursor IDE.
# Prompt
Events are emitted with Events.emit that triggers an action that does a DOM change (that does createElements or setAttribute for eample) and other events are emitted with Events.emit to notify of a change. Do a thorough search of the code base to list them all to write a exhaustive documentation. For each event tell me if it's to create a change or to notify a change. If it's an action and is not currently handled via an undoable command, please tell me. I'm not interested in events emitted with sceneEl.emit or el.emit, only list those emitted with Events.emit.
Please be exhaustive, here is a list that may help you: 
```
grep -r Events.emit src/
src/editor/index.js:    Events.emit('objectremove', object);
src/editor/index.js:        Events.emit('helperremove', this.helpers[node.uuid]);
src/editor/index.js:      Events.emit('entityselect', entity);
src/editor/index.js:    Events.emit('objectselect', object3D);
src/editor/index.js:    Events.emit('inspectortoggle', true);
src/editor/index.js:      Events.emit('objectfocus', focusEl.object3D);
src/editor/index.js:    Events.emit('inspectortoggle', false);
src/editor/components/viewport/CameraToolbar/CameraToolbar.component.js:    Events.emit(option.event, option.payload);
src/editor/components/viewport/TransformToolbar.js:    Events.emit(
src/editor/components/viewport/TransformToolbar.js:    Events.emit('transformmodechange', mode);
src/editor/components/viewport/TransformToolbar.js:    Events.emit('transformspacechanged', local ? 'local' : 'world');
src/editor/components/widgets/TextureWidget.js:    Events.emit('opentexturesmodal', this.state.value, (image) => {
src/editor/components/scenegraph/Entity.js:  onDoubleClick = () => Events.emit('objectfocus', this.props.entity.object3D);
src/editor/components/scenegraph/Toolbar.js:    Events.emit('updatescenegraph');
src/editor/components/scenegraph/Toolbar.js:        Events.emit('opensigninmodal');
src/editor/components/scenegraph/Toolbar.js:        Events.emit('openpaymentmodal');
src/editor/components/scenegraph/Toolbar.js:      Events.emit('opensigninmodal');
src/editor/components/scenegraph/Toolbar.js:      Events.emit('sceneplayingtoggle', false);
src/editor/components/scenegraph/Toolbar.js:    Events.emit('sceneplayingtoggle', true);
src/editor/components/scenegraph/Toolbar.js:              onClick={() => Events.emit('openscenesmodal')}
src/editor/components/scenegraph/Toolbar.js:              Events.emit('openscreenshotmodal');
src/editor/components/scenegraph/SceneGraph.js:        Events.emit('entityselect', entity);
src/editor/components/Main.js:            Events.emit('togglesidebar', { which: 'attributes' });
src/editor/components/Main.js:            Events.emit('togglesidebar', { which: 'scenegraph' });
src/editor/components/components/ProfileButton/ProfileButton.component.jsx:      return Events.emit('openprofilemodal');
src/editor/components/components/ProfileButton/ProfileButton.component.jsx:    return Events.emit('opensigninmodal');
src/editor/components/components/GeoPanel/GeoPanel.component.jsx:      Events.emit('opensigninmodal');
src/editor/components/components/GeoPanel/GeoPanel.component.jsx:      Events.emit('opengeomodal');
src/editor/components/components/GeoPanel/GeoPanel.component.jsx:      Events.emit('openpaymentmodal');
src/editor/components/components/Mixins.js:    Events.emit('entityupdate', {
src/editor/components/components/Mixins.js:    Events.emit('entityupdate', {
src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx:      Events.emit('hideAddLayerPanel');
src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx:      Events.emit('openpaymentmodal');
src/editor/components/components/CommonComponents.js:    Events.emit('entityidchange', entity);
src/editor/components/components/ActionBar/ActionBar.component.jsx:    Events.emit('hidecursor');
src/editor/components/components/ActionBar/ActionBar.component.jsx:    Events.emit('showcursor');
src/editor/components/modals/ScenesModal/ScenesModal.component.jsx:      Events.emit('updatescenegraph');
src/editor/components/modals/ProfileModal/ProfileModal.component.jsx:                    Events.emit('openpaymentmodal');
src/editor/lib/toolbar.js:  Events.emit('updatescenegraph');
src/editor/lib/toolbar.js:    Events.emit('updatescenegraph');
src/editor/lib/shortcuts.js:      Events.emit('openhelpmodal');
src/editor/lib/shortcuts.js:      Events.emit('transformmodechange', 'translate');
src/editor/lib/shortcuts.js:      Events.emit('transformmodechange', 'rotate');
src/editor/lib/shortcuts.js:      Events.emit('transformmodechange', 'scale');
src/editor/lib/shortcuts.js:      Events.emit('transformspacechange');
src/editor/lib/shortcuts.js:      Events.emit('togglegrid');
src/editor/lib/shortcuts.js:      Events.emit('togglemotioncapture');
src/editor/lib/shortcuts.js:        Events.emit('objectfocus', selectedEntity.object3D);
src/editor/lib/shortcuts.js:      Events.emit('cameraperspectivetoggle');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'left');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'right');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'top');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'bottom');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'back');
src/editor/lib/shortcuts.js:      Events.emit('cameraorthographictoggle', 'front');
src/editor/lib/shortcuts.js:      Events.emit('togglesidebar', { which: 'all' });
src/editor/lib/raycaster.js:      Events.emit('raycastermouseleave', null);
src/editor/lib/raycaster.js:    Events.emit(
src/editor/lib/raycaster.js:    Events.emit(
src/editor/lib/history.js:    Events.emit('historychanged', cmd);
src/editor/lib/history.js:      Events.emit('historychanged', cmd);
src/editor/lib/history.js:      Events.emit('historychanged', cmd);
src/editor/lib/history.js:    Events.emit('historychanged');
src/editor/lib/cameras.js:    Events.emit('cameratoggle', {
src/editor/lib/cameras.js:    Events.emit('cameratoggle', {
src/editor/lib/entity.js:      Events.emit('entityclone', clone);
src/editor/lib/commands/EntityRemoveCommand.js:    Events.emit('entityremoved', this.entity);
src/editor/lib/commands/EntityRemoveCommand.js:        Events.emit('entitycreated', this.entity);
src/editor/lib/commands/EntityCreateCommand.js:        Events.emit('entitycreated', this.entity);
src/editor/lib/commands/EntityCreateCommand.js:      Events.emit('entityremoved', this.entity);
src/editor/lib/commands/EntityRemoveComponentCommand.js:    Events.emit('componentremove', {
src/editor/lib/commands/EntityRemoveComponentCommand.js:    Events.emit('componentadd', {
src/editor/lib/commands/EntityAddComponentCommand.js:    Events.emit('componentadd', {
src/editor/lib/commands/EntityAddComponentCommand.js:    Events.emit('componentremove', {
src/editor/lib/commands/EntityUpdateCommand.js:    Events.emit('entityupdate', {
src/editor/lib/commands/EntityUpdateCommand.js:    Events.emit('entityupdate', {
src/editor/lib/assetsLoader.js:      Events.emit('assetsimagesload', this.images);
```
# Answer
I'll provide an exhaustive list of all Events.emit calls, categorizing them as either creating a change or notifying of a change. I'll also note if any action events are not currently handled via an undoable command.

1. objectremove
Purpose: Notify a change
Emitted in: src/editor/index.js

2. helperremove
Purpose: Notify a change
Emitted in: src/editor/index.js

3. entityselect
Purpose: Create a change
Emitted in: src/editor/index.js, src/editor/components/scenegraph/SceneGraph.js
Note: This is not currently handled via an undoable command.

4. objectselect
Purpose: Notify a change
Emitted in: src/editor/index.js

5. inspectortoggle
Purpose: Create a change
Emitted in: src/editor/index.js
Note: This is not currently handled via an undoable command.

6. objectfocus
Purpose: Create a change
Emitted in: src/editor/index.js, src/editor/components/scenegraph/Entity.js, src/editor/lib/shortcuts.js
Note: This is not currently handled via an undoable command.

7. updatescenegraph
Purpose: Notify a change
Emitted in: src/editor/components/scenegraph/Toolbar.js, src/editor/lib/toolbar.js, src/editor/components/modals/ScenesModal/ScenesModal.component.jsx

8. opensigninmodal, openpaymentmodal, openscenesmodal, openscreenshotmodal, openprofilemodal, opengeomodal, openhelpmodal
Purpose: Create a change
Emitted in: Various files (e.g., src/editor/components/scenegraph/Toolbar.js, src/editor/components/components/ProfileButton/ProfileButton.component.jsx, src/editor/lib/shortcuts.js)
Note: These are not currently handled via undoable commands.

9. sceneplayingtoggle
Purpose: Create a change
Emitted in: src/editor/components/scenegraph/Toolbar.js
Note: This is not currently handled via an undoable command.

10. togglesidebar
Purpose: Create a change
Emitted in: src/editor/components/Main.js, src/editor/lib/shortcuts.js
Note: This is not currently handled via an undoable command.

11. entityupdate
Purpose: Notify a change
Emitted in: src/editor/components/components/Mixins.js, src/editor/lib/commands/EntityUpdateCommand.js

12. entityidchange
Purpose: Notify a change
Emitted in: src/editor/components/components/CommonComponents.js

13. hidecursor, showcursor
Purpose: Create a change
Emitted in: src/editor/components/components/ActionBar/ActionBar.component.jsx
Note: These are not currently handled via undoable commands.

14. hideAddLayerPanel
Purpose: Create a change
Emitted in: src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx
Note: This is not currently handled via an undoable command.

15. transformmodechange, transformspacechange
Purpose: Create a change
Emitted in: src/editor/components/viewport/TransformToolbar.js, src/editor/lib/shortcuts.js
Note: These are not currently handled via undoable commands.

16. opentexturesmodal
Purpose: Create a change
Emitted in: src/editor/components/widgets/TextureWidget.js
Note: This is not currently handled via an undoable command.

17. togglegrid, togglemotioncapture
Purpose: Create a change
Emitted in: src/editor/lib/shortcuts.js
Note: These are not currently handled via undoable commands.

18. cameraperspectivetoggle, cameraorthographictoggle
Purpose: Create a change
Emitted in: src/editor/lib/shortcuts.js
Note: These are not currently handled via undoable commands.

19. raycastermouseleave
Purpose: Notify a change
Emitted in: src/editor/lib/raycaster.js

20. historychanged
Purpose: Notify a change
Emitted in: src/editor/lib/history.js

21. cameratoggle
Purpose: Create a change
Emitted in: src/editor/lib/cameras.js
Note: This is not currently handled via an undoable command.

22. entityclone
Purpose: Notify a change
Emitted in: src/editor/lib/entity.js

23. entityremoved
Purpose: Notify a change
Emitted in: src/editor/lib/commands/EntityRemoveCommand.js

24. entitycreated
Purpose: Notify a change
Emitted in: src/editor/lib/commands/EntityRemoveCommand.js, src/editor/lib/commands/EntityCreateCommand.js

25. componentremove, componentadd
Purpose: Notify a change
Emitted in: src/editor/lib/commands/EntityRemoveComponentCommand.js, src/editor/lib/commands/EntityAddComponentCommand.js

26. assetsimagesload
Purpose: Notify a change
Emitted in: src/editor/lib/assetsLoader.js

This list covers all the Events.emit calls in the codebase. Many of the events that create changes (like entityselect, inspectortoggle, and various modal openings) are not currently handled via undoable commands. Implementing undoable commands for these actions could improve the editor's undo/redo functionality and overall user experience.

**Comment by vincentfretin** [comment]
Probably `entityidchange` (but not used on 3dstreet) and `entityclone` (we would need to serialize to json the cloned entity) may be good candidates for undo. The other events are mainly related to the UI.

The purpose may not be accurate, it depends of the point of view, it can be considered an action that changes the React ui or select box in viewport (entityselect, objectselect).
sceneplayingtoggle purpose is both notify and an action, it triggers the change historyDisabled in history.js
inspectortoggle is actually between an action and notify, one change is done (this.opened set to true/false) before the event is emitted to do other changes.

**Comment by kfarr** [comment]
Wow this is a lot of refactoring! I took some time to look at all the changes

Here are some things I'm noticing
- instead of emiting event, `AFRAME.INSPECTOR.execute('componentadd', { ...`
- instead of bespoke create entity functions, using   `AFRAME.INSPECTOR.execute('entitycreate', newEntityObject);`
- default to create new entity as child of street-container, or if the object has `parentEl` property defined use that eg. `newEntityObject.parentEl = customGroupEl;`

things to test:
- behavior of adding entity -- will it go into segment container? or streets-container?
- all custom layers, street layers, random assets from each group
- test deleting those layers and others, note the message change should include entity name. also try undoing the remove
- go through the "flow": open old file > make changes > save new file with these changes > reload app > load the file to see if it displays correctly
- save / open new files

bugs found;
- undoing changing showground property on street component does not work (but it is the component that is nonstandard as it uses an additional `synchronize` property, therefore nothing to fix in this pr)

**Comment by rahulkgupta** [comment]
- behavior of adding entity -- will it go into segment container? or streets-container? goes under "User Layers"
- deleting and undoing seems to work. 
- save seems to persist but reloading app seems to run into some loading bug (probably unrelated)
- undo / redo multiple times doesnt work when undoing adding a layer. For example, i added a divider, moved it around a couple times and then undid until the layer was gone. i can't redo all the back to the position prior to undos

**Comment by vincentfretin** [comment]
There were indeed some issues.
The steps create, move, move, delete, undo, undo, undo, undo is now working properly.

**Comment by vincentfretin** [comment]
The behavior of adding entity has not changed when you click on a card.

**Comment by vincentfretin** [comment]
> There were indeed some issues. The steps create, move, move, delete, undo, undo, undo, undo is now working properly.

and the reverse redo, redo, redo, redo now works properly too.

**Comment by vincentfretin** [comment]
The scene graph is now properly updated to have the google 3d tiles child when setting the location, but the Geospatial Layers is still collapsed because we only expand the User Layers now. We can expand again the Geospatial Layers by default if you want, tell me if you want that.

**Comment by vincentfretin** [comment]
I want to do the undo duplicate and I think we should do final tests and merge that.
For undo select/unselect with an option to disable, we can do that in another PR later.

**Comment by vincentfretin** [comment]
I implemented the undo for the duplicate action (d shortcut).
I'm happy with the implementation, please do some more tests, if all is okay, we can merge.

**Comment by vincentfretin** [comment]
For the next things, I created:
- #801
- #802

**Comment by vincentfretin** [comment]
> * undoing changing showground property on street component does not work (but it is the component that is nonstandard as it uses an additional `synchronize` property, therefore nothing to fix in this pr)

No that was a bug in my implementation, fixed by https://github.com/3DStreet/3dstreet/pull/789/commits/0ca98b3c2e1890e77038e3bba48cb4f0587b9e27

**Comment by vincentfretin** [comment]
The latest commit is an edge case I have in my project, that may not be that important in your case. But I still verified we only get in the undo stack only the object with properties we set, and not all the properties.
Here when setting the street-geo component, updating it by changing the geoloc again and then manually removing the component:
image

**Comment by vincentfretin** [comment]
Some notes:
Having an id on an entity is mandatory for undo to work, especially in the case of the following steps: update position, delete, undo delete, undo update position, the recreated entity when we undo the delete will be different, that's why we keep entityId in the command entityupdate, and not the entity like it was the case when entityupdate was the only command we implemented. So each command will verify if we have an id, if we don't, we generate one with nanoid.
For entityremove command, we keep on the command an unloaded DOM clone (`prepareForSerialization`), so the deleted entity threejs resources are freed. Later if we need to serialize the undo stack, we can serialize that with `elementToJson` that is defined in #537

**Comment by vincentfretin** [comment]
I also tested the implementation in my project. I didn't find any other issue.
There is a command that I'll need in my project is transaction/batch command to run and undo atomically a set of commands, I didn't implement it yet.

**Comment by kfarr** [comment]
@vincentfretin thanks for all this work. Regarding nanoid, I think it's great to have autoid on our entities. I think the only issue with this is sometimes a user will be surprised to see an ID. For future work we could allow the end-user to more easily change `data-layer-display-name` so they can quickly change it to something else for display purposes while retaining the id underneath.

**Comment by vincentfretin** [comment]
The user shouldn't see the random id anywhere, if you still see it somewhere let me know it's an issue.
I modified the `getEntityDisplayName` function to never show the id, priority is displaying data-layer-name, class, mixin currently.
I now also use `getEntityDisplayName` for the delete dialog.

**Comment by kfarr** [comment]
did final testing, all looks good to me

feedback
- it looks like all drag-n-drop objects are placed in User Layer root by default and do not get placed as children of segments -- that is ok with me just confirming this is desired behavior
- note: intersection drag-n-drop does not respect 'position' from drop event, that is a separate task
- layer visibility via checkbox in scene graph is not an undo-able action, however editing `visible` as a property of `material` IS undo-able. We may want to revisit this in the future as part of https://github.com/3DStreet/3dstreet/issues/793

**Comment by vincentfretin** [comment]
> it looks like all drag-n-drop objects are placed in User Layer root by default and do not get placed as children of segments -- that is ok with me just confirming this is desired behavior

Yes that's correct, you said you wanted something simple for the drag and drop. ;)

> note: intersection drag-n-drop does not respect 'position' from drop event, that is a separate task

You have an issue for that?

**Pull request merged**
