### PR TITLE
street intersection 1.0

### PR DESCRIPTION
**Pull request by srothst1**
The goal of this pull request is to create a basic `intersection` component that developers can use to add intersections to their scenes in 3DStreet.

Here are some items that need to be tackled:

- [x] Account for invalid user input
- [x] Handle sidewalks
  - [x] Basic sidewalk functionality
  - [x] Fix sidewalk overlap
  - [x] Fix ordering that sidewalks are added
  - [x] Fix sidewalk footprint
  - [x] Fix sidewalk positioning
- [x] Switiching between intersection textures (crosswalk, no crosswalk)
- [x] Add corner curbs (https://github.com/3DStreet/3dstreet-assets/blob/main/sets/sidewalk-curb/gltf-exports/Corner-curb-1.glb)
- [x] Use the built in `position` property from an `a-entity`
- [x] Rename `scale` to `dimensions`
- [x] Support basic traffic signals and stop signs -> BACKLOG
- [x] Clean up how the intersection ground is defined. See `create-from-json-utils-tested.js` in the branch `driveways-1.0.`.
- [x] Use a sidewalk for the curbs. The API user should be able to specify both dimensions.
- [x] Remove the scanned curb model
- [x] Remove the crosswalk image.
- [x] Clean up code and run `lint`

Topics to discuss before merging:
- [x] Crosswalk stencils -> BACKLOG
- [x] General API design
- [x] Curb model scaling and quirks
- [x] Is the curb scaling constant? i.e. is the x and y scale uniform?

Here are some resources that I am using:
- https://glitch.com/edit/#!/3dstreet-loud-game?path=index.html%3A43%3A26
- https://aframe.io/docs/1.3.0/introduction/writing-a-component.html
- https://threejs.org/docs/#api/en/materials/MeshBasicMaterial
- https://threejs.org/docs/#api/en/textures/Texture

### CODE REVIEW

**Comment by srothst1** [comment]
Some code for testing
```js
<a-entity
  position="0 0 -35"
  id="left_street"
  street="length: 50"
  streetmix-loader="streetmixStreetURL: https://streetmix.net/kfarr/72/"
></a-entity>
<a-entity
  position="38 0 0"
  rotation = "0 90 0"
  id="perpendicular_street"
  street="length: 55"
  streetmix-loader="streetmixStreetURL: https://streetmix.net/srothst1/7/lapara; showBuildings: false;"
></a-entity>
<a-entity intersection="position: 0 -0.1 0; scale: 21 20;crosswalk: false;sidewalk: 0 0 0 0"></a-entity>
```

**Comment by srothst1** [comment]
Some screenshots:
`<a-entity intersection="position: 0 -0.1 0; scale: 21 20;crosswalk: false;sidewalk: 0 0 0 0"></a-entity>`
image

<a-entity intersection="position: 0 -0.1 0; scale: 21 20;crosswalk: true;sidewalk: 0 0 0 0"></a-entity>
image

**Comment by srothst1** [comment]
Feedback from @kfarr:
- use the built-in position property 
- rename scale to dimensions

**Comment by srothst1** [comment]
Here are some lingering `lint` issues that must be resolved:

```
/Users/srothst1/Desktop/3dstreet/src/index.js
  119:25  error  'THREE' is not defined  no-undef
  120:25  error  'THREE' is not defined  no-undef
  121:21  error  'THREE' is not defined  no-undef
```
Suggestions are welcomed.

**Comment by srothst1** [comment]
Hi @gnansai 👋 

Can you please combine `assets/signals/signalsystem1.glb` and `assets/signals/signalsystem2.glb` into a single `glTF`file? 

I'd like to be able to create `a-mixin` objects as follows:
```
  <a-asset-item id="signalsystem" src="${assetUrl}assets/signals/signalsystem.glb"></a-asset-item>
  <a-mixin id="signalsystem1" gltf-part-plus="src: #signalsystem; part: signalsystem1"></a-mixin>
  <a-mixin id="signalsystem2" gltf-part-plus="src: #signalsystem; part: signalsystem1"></a-mixin>
```

**Comment by gnansai** [comment]
Hi @srothst1 
I could not find the "signalsystem1.glb" in assets/signals
Could you point me to right set of the files?
image

**Comment by kfarr** [comment]
I have original blender files. That is best to use. Can this wait until I
can share this tomorrow?

**Comment by gnansai** [comment]
@kfarr sure,
Thanks :)

**Comment by kfarr** [comment]
@gnansai here is a new ticket for creating the signal models https://github.com/3DStreet/3dstreet/issues/168

**Comment by srothst1** [comment]
TODOs from convo with @kfarr:
- Use a sidewalk for the curb. User should be able to specify both dimensions. Should be an input for north west curb, south west curb, etc.
- remove the fancy curb model
- remove the crosswalk image

**Comment by srothst1** [comment]
- write up documentation for the intersection in readme

**Comment by kfarr** [comment]
good to merge, but still to do later:
- document
- signals and stop signs
- crosswalk striping

**Pull request merged**
