### PR TITLE
parking space markings

### PR DESCRIPTION
**Pull request by burritojustice**
adding T stencils to parking

### CODE REVIEW

**Comment by srothst1** [comment]
Hi everyone! Great pair programming session yesterday. What updates need to be implemented before this is ready to be merged?

**Comment by kfarr** [comment]
to complete:
- ensure t is properly aligned on x axis (not in the middle of the lane) for segments of varying widths
- ensure t markings are proper scale (length and width)
- ensure t markings are positioned appropriately for both inbound and outbound cases
- ensure t markings do not overlap with any other transparent stencil or lane striping
- bonus: change logic of [lane striping](https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L61) to not have white stripe between parking lane and drive lane once T markers are working as expected (source streetview of Mission street between 17th and 18th)

**Comment by srothst1** [comment]
Hi everyone! Some updates from this afternoon - here are some of the items that I have completed:
- ensure t is properly aligned on x axis (not in the middle of the lane) for segments of varying widths
- ensure t markings are proper scale (length and width)
- ensure t markings are positioned appropriately for both inbound and outbound cases
- ensure t markings are properly spaced (not sure what is standard, need to look this up)

Please note that we can use this street for testing: https://streetmix.net/srothst1/3/srothst1-test-parking

Here is an item that I am looking for guidance on:
- ensure t markings do not overlap with any other transparent stencil or lane striping

image

As we can see above, we already have transportation stencils that overlap in other lanes.

Here are some items that still need work:
- bonus: change logic of [lane striping](https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L61) to not have white stripe between parking lane and drive lane once T markers are working as expected (source streetview of Mission street between 17th and 18th)

**Comment by srothst1** [comment]
Sadly, I am getting the following error when trying to push my commits:
```
PS C:\Users\srothstein\Desktop\3dstreet> git push
remote: Permission to burritojustice/3dstreet.git denied to srothst1.
fatal: unable to access 'https://github.com/burritojustice/3dstreet.git/': The requested URL returned error: 403
```
Any suggestions? @kfarr it looks like you were able to make a commit, potnetially without @burritojustice's permission? However, this may be because you are the owner of the 3DStreet repository.

**Comment by burritojustice** [comment]
I added you two as contributors to the cloned repo on my end, hopefully that helped.

**Comment by kfarr** [comment]
Here are 2 screenshots from current repo:

17th street reference https://streetmix.net/kfarr/66/17th-street-existing-conditions
image

valencia street reference https://streetmix.net/burritojustice/15
image

**Comment by kfarr** [comment]
Experimentations with "+" instead of "T" marking

also removing white line separator markings between bike lane and parking lane
17th street
image

valencia concept
image

**Comment by kfarr** [comment]
Example from google satellite view valencia street SF between hill and 22nd
image

**Comment by kfarr** [comment]
Note streetmix rendering t pointing toward curb (instead of T pointing out from curb like in SF):
image

**Comment by kfarr** [comment]
Another experiment, manually positioning the cars on right side
image

**Comment by kfarr** [comment]
so basically 3 options:
- streetmix style (T pointed inward)
- San Francisco parking meter style (T pointed outward)
- do both with (+) marking instead

**Comment by burritojustice** [comment]
As bizarre as I find the SF version, I find the + kind of distracting -- like it's looking for additional meaning?

What about a less symmetrical + that is stretched in the vertical / Y axis?

Maybe this is just me, feel free to ignore this.

**Comment by kfarr** [comment]
Advice from a professional transportation engineer:
"I would go with T pointed inward [curbside] because I'm used to seeing T's, and then you don't have the issue of the stem of the T going into the next lane."

I just pushed [this commit](https://github.com/3DStreet/3dstreet/pull/144/commits/40e26f7007f8ae2fccc8d614ab1943667ade87f9) and I hope it's all to merge, what do you all think?

Here are pictures from it. I went with the brighter surface material as well

17th street example:
image

hypothetical valencia:
image

**Comment by srothst1** [comment]
We are close to being ready to merge this PR! I think this is great input:
```
"I would go with T pointed inward [curbside] because I'm used to seeing T's, and then you don't have the issue of the stem of the T going into the next lane."
```
Let's run with that 👍 

A few things to consider:
- Automatically placing one parked car in the middle of the parking lane street segment
- Randomly placing a random number of cars in the parking lane street segment

Thoughts?

**Comment by kfarr** [comment]
I would say this is good to go as-is, we can have separate tickets for adding cars since that is additive and doesn't require changes to what we've laid our here. Merging!

**Pull request merged**
