### PR TITLE
add perpendicular parking option

### PR DESCRIPTION
**Pull request by Algorush**
- refactor createDriveLaneElement function
- add perpendicular parking option

### CODE REVIEW

**Comment by Algorush** [comment]
Looks like I need to update some tests

**Comment by kfarr** [comment]
test street
http://localhost:7001/#https://streetmix.net/tomasborja21/1/university-blvd

**Comment by kfarr** [comment]
it looks mostly ok

except it should use white stripes betweens paces instead of the white + sign

i think you can use this mixin:
https://github.com/3DStreet/3dstreet/blob/main/src/assets.js#LL156

example image:
image

and yes to fix the failing tests. it does look like you moved some things around.

**Comment by Algorush** [comment]
added a temporary solution for correct texture rendering when using atlas-uvs

**Comment by kfarr** [comment]
@Algorush I think I merged it successfully...

**Pull request merged**
