### PR TITLE
add vehicles to the parking lane

### PR DESCRIPTION
**Pull request by srothst1**
The goal of this pull request is to add vehicles to the 

A few things to consider:

- Automatically placing one parked car in the middle of the parking lane street segment
- Randomly placing a random number of random vehicles in the parking lane street segment

@kfarr please let me know your thoughts on these options.

This pull request stems from the parking stencils added in the following pull request:
- https://github.com/3DStreet/3dstreet/pull/144

car

### CODE REVIEW

**Comment by srothst1** [comment]
Feel free to use this street for testing: https://streetmix.net/srothst1/3/srothst1-test-parking

**Comment by srothst1** [comment]
image

image

**Comment by srothst1** [comment]
Let's go with this:
- Automatically placing one parked car in the middle of the parking lane street segment

Because it best matches what streetmix currently has. Happy to update this later if necessary.

**Review by kfarr — APPROVED** [review]
looks great!

**Pull request merged**
