### PR TITLE
fix intersection saving issue

### PR DESCRIPTION
**Pull request by Algorush**
change intesection geometry primitive from plane to box and fix positions of intersection elements

### CODE REVIEW

**Comment by kfarr** [comment]
@Algorush thanks, do you mind describing a bit more the logic behind changing positions as part of the solution?
for example https://github.com/3DStreet/3dstreet/pull/341/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R173 and https://github.com/3DStreet/3dstreet/pull/341/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R147

**Comment by kfarr** [comment]
@Algorush the original issue appears resolved, but now there is a new regression: each of the 4 curbs (each corner of the intersection) is now higher than before.

You can see the difference in old and new screenshots below.

I also notice a lot of changes to z values in the diff of index.js:
https://github.com/3DStreet/3dstreet/pull/341/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R222

Why all the z value changes? Would reverting some of the z value changes fix the regression?

old:
image

new:
image

**Comment by Algorush** [comment]
To avoid problems with color and to make the intersection element the same as the rest with asphalt, I changed the primitive from plane to box for the element to which the intersection component is applied. After that, all child elements of the intersection slightly changed their z-axis relative to the scene. Therefore, I had to correct each type of element separately. But strange, I have not seen such offsets as in the screenshots. I will check again

**Comment by Algorush** [comment]
I'm still unable to reproduce the example of the z-position mismatch between curbs and footpath. Everything looks good on my local scene. Everything is good on this scene too: https://deploy-preview-341--3dstreet-core-builds.netlify.app/intersection.html

**Comment by kfarr** [comment]
@Algorush yes you're right, I was able to reproduce and it was my fault because of not using the latest json-utils that a second intersection scene was being added upon reload from json that was slightly offset, but the original is correctly placed. Anyway it's good to go

**Pull request merged**
