### PR TITLE
Night Mode

### PR DESCRIPTION
**Pull request by srothst1**
The goal of this pull request is to add a night mode to 3DStreet. Night mode is expected to be a part of the Loud Bicycle Game.

Here are some resources that I am using:
- https://glitch.com/edit/#!/sharp-geode-agenda
- https://github.com/kfarr/aframe-bus#links-to-codevember-2018-static-pages
- https://github.com/supermedium/aframe-environment-component
- https://aframe.io/docs/1.3.0/primitives/a-sky.html

### CODE REVIEW

**Comment by srothst1** [comment]
Screen Shot 2022-06-17 at 4 20 14 PM

**Comment by kfarr** [comment]
Looking good already! Added a ticket for gnanasai to help with the bus material:
https://github.com/3DStreet/3dstreet-assets/issues/28

**Comment by srothst1** [comment]
@kfarr sounds good! The bus stands out (in a bad way) - we need to update the bus material.

It would also be helpful if we had a more tightly scoped idea of what a completed version of night mode would look like. Happy to discuss this further...

**Comment by kfarr** [comment]
wip
image

**Comment by kfarr** [comment]
another option for a night sky image 
image

**Comment by kfarr** [comment]
Not in this release, but playing with different lighting.

These examples reduce the intensity of ambient light in index.js:
`      light.setAttribute('light', {type: 'ambient', color: '#FFF', intensity: 0.05});`
`      light2.setAttribute('light', {type: 'directional', color: '#FFF', intensity: 0.05});`

And add example spotlights under the streetlights in nightmode.html:
`        <a-entity class="light-streetlight" light="type:spot;angle:67.85;penumbra:1.19;intensity:4" position="7.213 7.5 -7.85" rotation="-90 0 0"></a-entity>`
`        <a-entity class="light-streetlight" light="type:spot;angle:67.85;penumbra:1.19;intensity:4" position="7.213 7.5 5.68" rotation="-90 0 0"></a-entity>`

Shadows are also an exercise for another day

image
image

**Pull request merged**
