### PR TITLE
Sidewalk Animation 1.0

### PR DESCRIPTION
**Pull request by srothst1**
The goal of this pull request is to add character animations to the sidewalks in 3DStreet.

Character animations can be added to the `sidewalk` segment by adding the variant string `animated`. For instance, we have:
```
  {
    "width": 9,
    "variantString": "normal|animated",
    "type": "sidewalk"
  }
```

Here are some relevant resources that I have used:
- https://aframe.io/docs/1.3.0/components/gltf-model.html
- https://github.com/n5ro/aframe-extras/blob/master/src/loaders/animation-mixer.js
- https://aframe.io/docs/1.3.0/components/animation.html#api_to
- https://glitch.com/edit/#!/deep-cliff-bay

### CODE REVIEW

**Comment by srothst1** [comment]
Screen Shot 2022-06-13 at 12 53 49 PM

Here is a short video of what I have so far: https://youtu.be/z-4lTyBECC8

Please keep in mind that we can tweak the speed, timing, etc.

**Comment by srothst1** [comment]
Screen Shot 2022-06-13 at 12 53 42 PM

Here is a video of what I have so far: https://youtu.be/z-4lTyBECC8

Please keep in mind that we can tweak parameters such as speed, duration, etc.

**Comment by srothst1** [comment]
This `JSON` file can be used for testing:
```
<a-entity id="test" street='left: narrow; right: fence; JSON:
{
  "streetmixSegmentsFeet": [
    {
      "width": 9,
      "variantString": "outbound",
      "type": "drive-lane"
    },
    {
      "width": 9,
      "variantString": "dense",
      "type": "sidewalk"
    },
    {
      "width": 4,
      "variantString": "empty",
      "type": "sidewalk"
    },
    {
      "width": 9,
      "variantString": "sparse|animated",
      "type": "sidewalk"
    },
    {
      "width": 4,
      "variantString": "empty",
      "type": "sidewalk"
    },
    {
      "width": 9,
      "variantString": "normal",
      "type": "sidewalk"
    },
    {
      "width": 20,
      "variantString": "normal|animated",
      "type": "sidewalk"
    }
  ]
}'></a-entity>
```

**Comment by srothst1** [comment]
Hi @kfarr 👋 

Can you please let me know what needs to be updated or modified? I am not sure what else is in the scope of this PR.

**Comment by kfarr** [comment]
some initial feedback:
- I had to add `<script src="//cdn.8thwall.com/web/aframe/aframe-extras-6.1.1.min.js"></script>` to index.html to get animations to work
- the duration of first animation appears to be identical for all pedestrians regardless of location, resulting in all arriving at the same time. instead the duration of the first animation should be dynamic depending on distance of pedestrian to the edge.
- pedestrians traveling in opposite directions upon second animation collide directly

**Comment by srothst1** [comment]
Hi @kfarr, thank you very much for the feedback. I added a few commits that should address these issues 👍

**Comment by srothst1** [comment]
I have noticed some interesting behavior. If I leave the animation running as a background process for 5-10 minutes, sometimes some of the character animations will sync up. Specifically, the character animations (`animation__2`) are synched to start at the same time.

I am not sure what is causing this issue. It's possible that this issue is caused by how Safari caches memory or pauses processes.

**Pull request merged**
