### PR TITLE
New scene function

### PR DESCRIPTION
**Pull request by Algorush**
Added a newScene function to clear the old scene and create an empty scene. Perhaps there is something else to consider in this function, @kfarr ?
In the next commits I will add call of this function to the appropriate places in the code.
https://github.com/3DStreet/3dstreet/issues/485

### CODE REVIEW

**Comment by Algorush** [comment]
what should be the initial structure of Blank Scene? Like this one?
```
      <a-entity id="street-container" data-layer-name="3D Street Layers" data-layer-show-children>
        <a-entity id="default-street" set-loader-from-hash></a-entity>
      </a-entity>
      <a-entity id="reference-layers" data-layer-name="Reference Layers" data-layer-show-children></a-entity>
      <a-entity id="environment" data-layer-name="Environment" street-environment="preset: day;"></a-entity>
```

**Comment by Algorush** [comment]
I have added newScene funtion as STREET.utils.newScene. I added a call to this function in the appropriate scene loading methods, including in the Editor code, in this PR: https://github.com/3DStreet/3dstreet-editor/pull/420

**Comment by kfarr** [comment]
things this does not reset yet:
* currently selected object blue bounding box
* long / lat / elevation in geopanel above scene title
* camera pose (position and rotation) -- this is probably ok to leave for a later date

image

**Comment by kfarr** [comment]
similar to scene title edit modal, when the street-geo component is updated, we should also fire an event such that the react app is listening for this event and 'resets' the geo panel?

**Comment by vincentfretin** [comment]
> similar to scene title edit modal, when the street-geo component is updated, we should also fire an event such that the react app is listening for this event and 'resets' the geo panel?

@kfarr and I started a GeoContext on @kfarr machine. Almost finished, we just need to reset the context value after calling newScene. We will finish that Friday.

**Comment by vincentfretin** [comment]
Also probably put the "New" button behind a flag or just comment it before merging.
Like discussed, just having a new blank scene, without some templates or onboarding is confusing for the user.

**Comment by kfarr** [comment]
@vincentfretin i committed our WIP work and tested, all seems to work with exception of resetting geo stuff as you noted so we can resume that on Fri

**Pull request merged**
