### PR TITLE
new coat of paint 3.0

### PR DESCRIPTION
**Pull request by srothst1**
# new coat of paint 3.0

The goal of this pull request is add the camera selector the the 3DStreet viewer.

Here is the list of TODOs:

- [x] The hover state on the "Cross section" option in the camera selector needs to be tweaked slightly. I have asked Ajay to take a look at this (see UpWork).
- [ ] The overall hover state UI is not quite perfect (but might be passible?)
image
- [x] Run `lint`

Here are some resources that I have been using to guide me through this process:
- Front end UI elements from Ajay: https://github.com/AJAY9589/3dstreet_ui
- @kfarr's multi-camera demo: https://github.com/kfarr/aframe-multi-camera/tree/main/examples
- The `aframe-multi-camera` documentation: https://github.com/diarmidmackenzie/aframe-multi-camera

### CODE REVIEW

**Comment by srothst1** [comment]
I need guidance on the following topics:
- Should we hide the camera selector if someone is using the 3DStreet viewer on mobile?
- I am currently placing the four additional cameras (Perspective, Plan View, Cross Section, Side View) manually. Their positions are set as follows:
  ```js
  <a-entity id="camera1" secondary-camera="outputElement:#viewport1" position = "-15 12 20" rotation="-15 -45 0"></a-entity>
  <a-entity id="camera2" secondary-camera="outputElement:#viewport2" position = "0 50 0" rotation="-90 0 0"></a-entity>
  <a-entity id="camera3" secondary-camera="outputElement:#viewport3" position = "0 5.6 -50" rotation="0 180 0"></a-entity>
  <a-entity id="camera4" secondary-camera="outputElement:#viewport4" position = "-30 15 0" rotation="-18 -90 0"></a-entity>
  ```
  While this works fine for a single street of length 50m-150m, it's easy to see how this solution might not be optimal for a more intricate scene configuration with multiple streets. Any suggestions for how to place these cameras more optimally? Is this beyond the scope of this PR? This issue seems partially product related.
- I'm struggling to properly update the camera position, rotation, and panning when the camera selector UI is used to change the camera perspective. Currently, the following code is updating the main camera:
  ```js
  function perspectiveCamera() {
    document.getElementById("camera").setAttribute('orbit-controls', "autoRotate: false;autoRotateSpeed:0.01;target: 0 0 0;enableKeys:false");
    document.getElementById("camera").setAttribute('camera', "");
    document.getElementById("camera").setAttribute('position', "-15 12 20");
    document.getElementById("camera").setAttribute('rotation', "-15 -45 0");
  }
  function planViewCamera() {
    document.getElementById("camera").setAttribute('orbit-controls', "autoRotate: false;autoRotateSpeed:0.01;target: 0 0 0;enableKeys:false");
    document.getElementById("camera").setAttribute('camera', "");
    document.getElementById("camera").setAttribute('position', "0 50 0");
    document.getElementById("camera").setAttribute('rotation', "-90 0 0");
  }
  function crossSectionCamera() {
    document.getElementById("camera").setAttribute('orbit-controls', "autoRotate: false;autoRotateSpeed:0.01;target: 0 0 0;enableKeys:false");
    document.getElementById("camera").setAttribute('camera', "");
    document.getElementById("camera").setAttribute('position', "0 5.6 -50");
    document.getElementById("camera").setAttribute('rotation', "0 180 0");
  }
  function sideViewCamera() {
    document.getElementById("camera").setAttribute('orbit-controls', "autoRotate: false;autoRotateSpeed:0.01;target: 0 0 0;enableKeys:false");
    document.getElementById("camera").setAttribute('camera', "");
    document.getElementById("camera").setAttribute('position', "-30 15 0");
    document.getElementById("camera").setAttribute('rotation', "-18 -90 0");
  }
  ```
  This code produces the following result:
  https://drive.google.com/file/d/1h_TNWNsg4nQ5ONwvck6JvvD8W-i_XH_m/view?usp=sharing
- In order to get the `aframe-multi-camera`  working, I had to comment out the following lines of code:
  ```html
  <a-cubemap id="skycube">
    <img src="assets/images/skybox/posx.jpg">
    <img src="assets/images/skybox/negx.jpg">
    <img src="assets/images/skybox/posy.jpg">
    <img src="assets/images/skybox/negy.jpg">
    <img src="assets/images/skybox/posz.jpg">
    <img src="assets/images/skybox/negz.jpg">
  </a-cubemap>
  ```
  Should this be a permanent change, or is there another workaround? I revieve the following error when those lines are not commented out:
  ```js
  three.js:20378 Uncaught RangeError: Maximum call stack size exceeded
      at setProgram (three.js:20378:1)
      at WebGLRenderer.renderBufferDirect (three.js:19887:1)
      at renderObject (three.js:20278:1)
      at renderObjects (three.js:20254:1)
      at renderScene (three.js:20205:1)
      at WebGLRenderer.render (three.js:20084:1)
      at o.render (multi-camera.js:66:27)
      at PMREMGenerator._textureToCubeUV (three.js:11811:1)
      at PMREMGenerator._fromTexture (three.js:11680:1)
      at PMREMGenerator.fromCubemap (three.js:11619:1)
  ```
   See https://github.com/diarmidmackenzie/aframe-multi-camera/issues/2

**Comment by srothst1** [comment]
From @kfarr and @srothst1 discussion:
- Fixed camera positions are okay for now
- No auto rotate -> remove this from the current implementation
- On mobile, no hover state -> handled by Ajay
- See how the inspector is handling camera switching

**Comment by srothst1** [comment]
Hi @diarmidmackenzie 👋 I was hoping that you could help me get this pull request merged. I'm struggling with two primary issues. I have outlined them in the first two bullet points of [this comment](https://github.com/3DStreet/3dstreet/pull/157#issuecomment-1115135378).

**Comment by diarmidmackenzie** [comment]
Hi @srothst1 - not clear to me exactly what you want help with.

The first 2 bullets of the comment you linked to are:

> "I am currently placing the four additional cameras (Perspective, Plan View, Cross Section, Side View) manually. ..."

That seems more like a product design question.  I don't think I can help with that?

and

> "I'm struggling to properly update the camera position, rotation, and panning when the camera selector UI is used to change the camera perspective...."

I'm not sure I understand the problem here.  I watched the linked video, and it looks like the main camera position / orientation gets updated when the user selects a particular view.  It's not obvious to me what's wrong with that - i.e. what's the problem here that you would like my help with?

A point I can help with is this one:

> "In order to get the aframe-multi-camera working, I had to comment out the following lines of code..."

I already provided a fix for this - see my last comment here: https://github.com/diarmidmackenzie/aframe-multi-camera/issues/2

Can you reply on that issue to confirm whether the fix worked?

**Review by AJAY9589 — APPROVED** [review]

**Comment by diarmidmackenzie** [comment]
@srothst1 No I hadn't tried running it myself yet.

I'm a bit busy this weekend, but will take a look on Monday.

**Comment by diarmidmackenzie** [comment]
From your description, it sounds very much like a problem I had with repositioning/reorienting the camera in blocksarcade.

See the "scene-jumps" component for how I solved it there.

https://github.com/diarmidmackenzie/blocks-arcade/blob/2d2c9a89e4957e6bb0290213b64f7f03f16873b6/src/blocksarcade-utils.js#L331

**Comment by diarmidmackenzie** [comment]
Specifically, override the internal pitch and yaw data in 'look-controls' rather than modifying the camera rotation attribute directly.

**Comment by srothst1** [comment]
Hi @diarmidmackenzie. Great, I am happy to hear that you are going to take a quick look 😀

**Comment by srothst1** [comment]
this seems like a plausible solution 
```
override the internal pitch and yaw data in 'look-controls'
```

**Comment by diarmidmackenzie** [comment]
Ok, I had a play with it - seems like composing multiple camera movements (pans / zooms) + changes of view is what leads to problems.  I think that's very likely due to modifying the camera rotation directly, and can be fixed by modifying the look-controls pitch & yaw instead, as per my note above.

I suggest you make that change, and if it's still not working I'm happy to take another look.

**Comment by srothst1** [comment]
Hi @diarmidmackenzie. I really appreciate the feedback. Your suggestion seems to do the trick.

**Comment by kfarr** [comment]
closing for another day

**Pull request closed without merging**
